$base    = rgba(1f1d2eff)
$surface = rgba(191724ff)
$text    = rgba(e0def4ff)
$love    = rgba(eb6f92ff)
$pine    = rgba(31748fff)
$foam    = rgba(9ccfd8ff)

general {
    ignore_empty_input = true
}

animations {
    enabled = true
    animation = fadeIn,  1, 3, default
    animation = fadeOut, 1, 3, default
}

background {
    monitor =
    path  = screenshot
    color = rgba(1f1d2e80)

    blur_passes = 1
    blur_size = 1

    contrast = 1
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

label {
    monitor     = $ACTIVE_MONITOR
    text        = $TIME
    color       = $text
    font_size   = 72
    font_family = CaskaydiaCove Nerd Font Mono 9
    position    = 0, 180
    halign      = center
    valign      = center
}

label {
    monitor     = $ACTIVE_MONITOR
    text        = cmd[update:60000] date '+%a, %B %-e'
    color       = $text
    font_size   = 22
    font_family = CaskaydiaCove Nerd Font Mono 9
    position    = 0, 100
    halign      = center
    valign      = center
}

input-field {
    monitor = $ACTIVE_MONITOR
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgba(144, 144, 144, 0.8)
    fade_on_empty = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    placeholder_text = <i><span foreground="##cdd6f4">Enter Password...</span></i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

shape {
    monitor = $ACTIVE_MONITOR
    size = 250, 100
    color = rgba(24283bff)
    rounding = 1
    border_size = 2
    border_color = rgba(73DACAff)

    position = -5, -35
    halign = right
    valign = top
}

image {
    monitor     = $ACTIVE_MONITOR
    path        = /tmp/hyprlock-art.png
    reload_time = 0
    size        = 80
    rounding    = 10
    position    = -163, -42
    halign      = right
    valign      = top
}

label {
    monitor = $ACTIVE_MONITOR
    text        = cmd[update:1000] ~/.config/hypr/scripts/now_playing.sh
    text_align  = left
    color = rgba(E5E4D9ff)
    font_size = 10
    font_family = CaskaydiaCove Nerd Font Mono 9
    position    = -12, -42
    halign      = right
    valign      = top
}
