##########@###################
# ----- Standard Stuff ----- #
###########@##################

format = '''
\[[$username@$hostname](#45F1C2)\][--](red)\[$shell\][--](red)\[$directory\][--](red)\[$git_branch $git_status\]$all
[→ ](#E06C75)
'''

[username]
show_always = true

format = '$user'

[hostname]
disabled = false

format = '$hostname'

ssh_only = false
ssh_symbol = " "

[shell]
disabled = false

style = '#14A5AE'
format = '[ $indicator]($style)'

[directory]
truncation_length = 10
truncate_to_repo = false
truncation_symbol = '.../'

style = '#0CA0D8'
format = '[ $path]($style)[$read_only]($read_only_style)'

before_repo_root_style = "#0CA0D8"
repo_root_style = "bold #0dd8a9"
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
read_only = " 󰌾"
use_logical_path = false

### Git ###

[git_branch]
symbol = ''
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
staged = '  ${count}'
modified = '  ${count}'

format = '[$ahead_behind](#F3C267)[$all_status](#FF9248)'

####@###########################
# ----- NerdFont Symbols ----- #
#####@##########################

[docker_context]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[package]
symbol = "󰏗 "

### OS SYMBOLS ###

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

### LANGUAGES / PACKAGE VERSIONS ##

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
