"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#45F1C2"
  style = "plain"
  template = "[{{ .UserName }}@{{ .HostName }}]"
  type = "text"

  [[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "#14A5AE"
  template = "<#ffffff>--</>[ {{ .Name }}]"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#B388FF"
  template = "{{ if .Env.IN_NIX_SHELL }}<#ffffff>--</>[󱄅 nix-{{ .Env.IN_NIX_SHELL }}]{{ end }}"

  [[blocks.segments]]
  foreground = "#F3C267"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
]
  style = "plain"
  template = "<#ffffff>--</>[{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}]"
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  template = " x{{ reason .Code }}"

  [[blocks.segments]]
  foreground = "#b8ff75"
  foreground_templates = [ "{{ if gt .Code 0 }}#E06C75{{ end }}" ]
  style = "diamond"
  template = " {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    style = "roundrock"
    always_enabled = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#0CA0D8"
  style = "plain"
  template = " {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    style = "full"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#E06C75"
  style = "plain"
  template = "!"
  type = "root"

  [[blocks.segments]]
  foreground = "#E06C75"
  style = "plain"
  template = "→"
  type = "text"

